<% adapter = 'sqlite3' %>
<% adapter = 'jdbcsqlite3' if(Guards::jruby? ) %>

test_mysql:
  adapter: jdbcmysql
  database: ar_loader_test
  username: test
  password: test
  host: localhost

test_memory:
  adapter: <%= adapter %>
  database: :memory

test_file:
  adapter: <%= adapter %>
  database: 'ar_loader_test'
  encoding: utf8
  host: localhost